Dockerification
DavidNemeskey/cc_corpus pull request #64
Opened 2024-05-21 06:32 UTC by acheronw

2024-05-21 09:24 UTC, DavidNemeskey requested changes

2024-05-21 13:19 UTC, acheronw commented on Dockerfile
> +EXPOSE 8000
Good questions. Currently the manager webapp has 0 security features. We should add some at a later point, but I agree that this is beyond the scope of this merge.

2024-05-21 13:46 UTC, acheronw commented on Dockerfile
> +RUN echo 'conda activate cc_corpus ' >> ~/.bashrc
You are right it is not.

2024-05-27 15:35 UTC, DavidNemeskey approved these changes

2024-05-27 15:35 UTC, merged